global:
  resolve_timeout: 2m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  wechat_api_secret: '...'
  wechat_api_corp_id: '...'


templates:
  - '/usr/local/alertmanager/template/wechat.tmpl'
route:
  receiver: wechat
  group_by:
  - alertname_wechat
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
receivers:
- name: 'wechat'
  wechat_configs:
  - corp_id: '....'
     #to_party: '62'
    to_user: '...'
    agent_id: '...'
    api_secret: '...'
    send_resolved: true
    http_config: {}
    message: '{{ template "wechat.default.message" . }}'
    api_url: https://qyapi.weixin.qq.com/cgi-bin/
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
